version: '3'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/src
    command: python /var/src/main.py
    hostname: api
    ports:
      - "5000:5000"
    environment:
      MY_IP: ${MY_IP}
  tweepy:
    build:
      context: ./twitter-scrapping
    volumes:
      - ./twitter-scrapping:/var/src
    environment:
      MY_IP: ${MY_IP}
    command: python /var/src/main.py
    depends_on:
      - "kafka"
    env_file:
      - ./.env_tweepy
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "7203:7203"
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "PythonTest:1:1"
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - "zookeeper"
  db:
    build:
      context: ./db
    volumes:
      - ./db:/var/src
    command: python /var/src/app.py
    environment:
      MY_IP: ${MY_IP}
    env_file:
      - ./.env_tweepy
  mongo:
    image: mongo
    ports:
      - "27017:27017"

